version: 2.1
orbs:
    cypress: cypress-io/cypress@1.13.0
executors:
    base10:
        docker:
            - image: 'cypress/included:3.6.1'
workflows:
    version: 2
    build:        
        jobs:            
            #- cypress/install
            - cypress/run:
                executor: base10
                browser: chrome
                record: false # record Cypress tests on the Dashboard
                command: 'npm run cy:run'
            - store_artifacts:
                    path: cypress/videos
            - store_artifacts:
                    path: cypress/screenshots
            - store_artifacts:
                    path: cypress/report
                
    scheduled:
        triggers:
            - schedule:
                cron: "0 8,14 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - cypress/run:
                  executor: base10
                  browser: chrome
                  record: false
                  store_artifacts: true
                  command: 'npm run cy:run'
            - store_artifacts:
                    path: cypress/videos
            - store_artifacts:
                    path: cypress/screenshots
            - store_artifacts:
                    path: cypress/report