version: 2.1
orbs:
    cypress: cypress-io/cypress@1.13.0
executors:
    base10:
        docker:
            - image: 'cypress/included:3.6.1'
workflows:
    build:
        jobs:
            # record Cypress tests on the Dashboard
            - cypress/install
            - cypress/run:
                  executor: base10
                  browser: chrome
                  record: false
                  store_artifacts: true
                  command: 'npm run cy:run'
            triggers:
            - schedule:
                cron: "0 8,14,15 * * *"
                filters:
                    branches:
                    only:
                        - master
        
